# Generated by Django 2.2.1 on 2019-05-14 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCodes',
            fields=[
                ('zip_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=10)),
                ('bedrooms', models.CharField(max_length=2)),
                ('bathrooms', models.CharField(max_length=2)),
                ('type', models.CharField(max_length=99)),
                ('price', models.CharField(max_length=999)),
                ('on_sale', models.BooleanField()),
                ('more_info', models.CharField(max_length=999)),
                ('main_image', models.CharField(default='https://image.shutterstock.com/image-vector/simple-house-icon-white-flat-260nw-1086201605.jpg', max_length=999)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstate.ZipCodes')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=9999)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstate.RealEstates')),
            ],
        ),
    ]
